# Water Quality Prediction

### Competition : Water, water everywhere, not a drop to drink!
#### Kaggle Days Meet Up - 2

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("../input/water-water-everywhere-not-a-drop-to-drink/train.csv")
test = pd.read_csv("../input/water-water-everywhere-not-a-drop-to-drink/test.csv")
submission = pd.read_csv("../input/water-water-everywhere-not-a-drop-to-drink/sample_submission.csv")

In [3]:
data.shape

(13000, 28)

In [4]:
data.head()

,id,categoryA,categoryB,categoryC,categoryD,categoryE,categoryF,featureA,featureB,featureC,...,compositionC,compositionD,compositionE,compositionF,compositionG,compositionH,compositionI,compositionJ,unit,result
0,a563699ca2a601c6ac64aa29986a00a90fb42b48741695...,catA_1,catB_0,catC_718,catD_0,catE_0,catF_0,75808.375,4.457840,0.005718,...,26.0,0.0,32.0,3.0,0.0,9.0,22.26,20.0,unit_6,0.000458
1,91ab3eb3bcf6c8c1c5fe2da9ba671aa5a48c7369d9a50f...,catA_1,catB_0,catC_1309,catD_0,catE_0,catF_0,75808.375,4.457840,0.005718,...,26.0,0.0,32.0,3.0,0.0,9.0,22.26,20.0,unit_6,0.000335
2,7128c51c554735d6c81862684ad6005ae12d2edbcd4644...,catA_15,catB_0,catC_1309,catD_0,catE_0,catF_0,75808.375,4.457840,0.005718,...,26.0,0.0,32.0,3.0,0.0,9.0,22.26,20.0,unit_4,0.054072
3,c8144b52e4f63014de0a0d8e1c629bf0b05cb2696cfc23...,catA_0,catB_0,catC_935,catD_0,catE_0,catF_0,75808.375,4.457840,0.005718,...,26.0,0.0,32.0,3.0,0.0,9.0,22.26,20.0,unit_5,0.061143
4,88d15a5b2df6692f23d105ff1ae82ae026be00c9271eef...,catA_22,catB_0,catC_1325,catD_0,catE_2,catF_0,-40055.250,4.363288,0.729194,...,14.0,0.0,49.0,3.0,2.0,9.0,16.84,15.0,unit_15,0.015439

In [5]:
data.columns

Index(['id', 'categoryA', 'categoryB', 'categoryC', 'categoryD', 'categoryE',
       'categoryF', 'featureA', 'featureB', 'featureC', 'featureD', 'featureE',
       'featureF', 'featureG', 'featureH', 'featureI', 'compositionA',
       'compositionB', 'compositionC', 'compositionD', 'compositionE',
       'compositionF', 'compositionG', 'compositionH', 'compositionI',
       'compositionJ', 'unit', 'result'],
      dtype='object')

In [6]:
data.describe(include='object')

,id,categoryA,categoryB,categoryC,categoryD,categoryE,categoryF,unit
count,13000,13000,13000,13000,13000,13000,13000,13000
unique,13000,167,2,2212,3,25,3,19
top,a563699ca2a601c6ac64aa29986a00a90fb42b48741695...,catA_1,catB_0,catC_2,catD_0,catE_0,catF_0,unit_0
freq,1,853,12989,43,12657,6441,12967,2548

In [7]:
y = data['result']
data = data.drop(['result'],axis = 1)

In [8]:
data = data.drop(['id'],axis = 1)

In [9]:
cat = (data.dtypes == 'object')
object_cols = list(cat[cat].index)

In [10]:
print("Categorical variables are:")
print(object_cols)

Categorical variables are:
['categoryA', 'categoryB', 'categoryC', 'categoryD', 'categoryE', 'categoryF', 'unit']

In [11]:
cat_data = data[object_cols]

test_cat_data = test[object_cols]

In [12]:
cat_data.head()

  categoryA categoryB  categoryC categoryD categoryE categoryF     unit
0    catA_1    catB_0   catC_718    catD_0    catE_0    catF_0   unit_6
1    catA_1    catB_0  catC_1309    catD_0    catE_0    catF_0   unit_6
2   catA_15    catB_0  catC_1309    catD_0    catE_0    catF_0   unit_4
3    catA_0    catB_0   catC_935    catD_0    catE_0    catF_0   unit_5
4   catA_22    catB_0  catC_1325    catD_0    catE_2    catF_0  unit_15

In [13]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

cat_data['categoryA'] = label_encoder.fit_transform(cat_data['categoryA'])
cat_data['categoryC'] = label_encoder.fit_transform(cat_data['categoryC'])
cat_data['categoryE'] = label_encoder.fit_transform(cat_data['categoryE'])
cat_data['unit'] = label_encoder.fit_transform(cat_data['unit'])

test_cat_data['categoryA'] = label_encoder.fit_transform(test_cat_data['categoryA'])
test_cat_data['categoryC'] = label_encoder.fit_transform(test_cat_data['categoryC'])
test_cat_data['categoryE'] = label_encoder.fit_transform(test_cat_data['categoryE'])
test_cat_data['unit'] = label_encoder.fit_transform(test_cat_data['unit'])

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

In [14]:
cat_data.head()

   categoryA categoryB  categoryC categoryD  categoryE categoryF  unit
0          1    catB_0       1925    catD_0          0    catF_0    15
1          1    catB_0        287    catD_0          0    catF_0    15
2         49    catB_0        287    catD_0          0    catF_0    13
3          0    catB_0       2146    catD_0          0    catF_0    14
4         82    catB_0        302    catD_0         11    catF_0     7

In [15]:
cat_data.shape

(13000, 7)

In [16]:
cat_data = pd.get_dummies(cat_data,columns=['categoryB','categoryD','categoryF'])

test_cat_data = pd.get_dummies(test_cat_data,columns=['categoryB','categoryD','categoryF'])

In [17]:
cat_data.shape

(13000, 12)

In [18]:
test_cat_data.shape

(7000, 12)

In [19]:
cat_data.head()

,categoryA,categoryC,categoryE,unit,categoryB_catB_0,categoryB_catB_1,categoryD_catD_0,categoryD_catD_1,categoryD_catD_2,categoryF_catF_0,categoryF_catF_1,categoryF_catF_2
0,1,1925,0,15,1,0,1,0,0,1,0,0
1,1,287,0,15,1,0,1,0,0,1,0,0
2,49,287,0,13,1,0,1,0,0,1,0,0
3,0,2146,0,14,1,0,1,0,0,1,0,0
4,82,302,11,7,1,0,1,0,0,1,0,0

In [20]:
test_cat_data.head()

,categoryA,categoryC,categoryE,unit,categoryB_catB_0,categoryB_catB_1,categoryD_catD_0,categoryD_catD_1,categoryD_catD_2,categoryF_catF_0,categoryF_catF_1,categoryF_catF_2
0,99,1415,1,16,1,0,1,0,0,1,0,0
1,99,435,0,16,1,0,1,0,0,1,0,0
2,51,274,8,4,1,0,1,0,0,1,0,0
3,88,716,0,0,1,0,1,0,0,1,0,0
4,88,201,12,0,1,0,1,0,0,1,0,0

In [21]:
num_data = data.select_dtypes(exclude=['object'])
test_num_data = test.select_dtypes(exclude=['object'])

In [22]:
num_data.head()

,featureA,featureB,featureC,featureD,featureE,featureF,featureG,featureH,featureI,compositionA,compositionB,compositionC,compositionD,compositionE,compositionF,compositionG,compositionH,compositionI,compositionJ
0,75808.375,4.457840,0.005718,122.299437,30.831906,0.0,2.806036e+12,0.000000,71176346.0,0.0,10.0,26.0,0.0,32.0,3.0,0.0,9.0,22.26,20.0
1,75808.375,4.457840,0.005718,122.299437,30.831906,0.0,2.806036e+12,0.000000,71176346.0,0.0,10.0,26.0,0.0,32.0,3.0,0.0,9.0,22.26,20.0
2,75808.375,4.457840,0.005718,122.299437,30.831906,0.0,2.806036e+12,0.000000,71176346.0,0.0,10.0,26.0,0.0,32.0,3.0,0.0,9.0,22.26,20.0
3,75808.375,4.457840,0.005718,122.299437,30.831906,2.0,2.806036e+12,0.000000,71176346.0,0.0,10.0,26.0,0.0,32.0,3.0,0.0,9.0,22.26,20.0
4,-40055.250,4.363288,0.729194,93.677197,15.047884,4.0,1.464509e+12,87.158924,50941692.0,0.0,8.0,14.0,0.0,49.0,3.0,2.0,9.0,16.84,15.0

In [23]:
new_data = pd.concat([num_data,cat_data],axis=1)

test_new_data = pd.concat([test_num_data,test_cat_data],axis=1)

In [24]:
new_data.head()

,featureA,featureB,featureC,featureD,featureE,featureF,featureG,featureH,featureI,compositionA,...,categoryE,unit,categoryB_catB_0,categoryB_catB_1,categoryD_catD_0,categoryD_catD_1,categoryD_catD_2,categoryF_catF_0,categoryF_catF_1,categoryF_catF_2
0,75808.375,4.457840,0.005718,122.299437,30.831906,0.0,2.806036e+12,0.000000,71176346.0,0.0,...,0,15,1,0,1,0,0,1,0,0
1,75808.375,4.457840,0.005718,122.299437,30.831906,0.0,2.806036e+12,0.000000,71176346.0,0.0,...,0,15,1,0,1,0,0,1,0,0
2,75808.375,4.457840,0.005718,122.299437,30.831906,0.0,2.806036e+12,0.000000,71176346.0,0.0,...,0,13,1,0,1,0,0,1,0,0
3,75808.375,4.457840,0.005718,122.299437,30.831906,2.0,2.806036e+12,0.000000,71176346.0,0.0,...,0,14,1,0,1,0,0,1,0,0
4,-40055.250,4.363288,0.729194,93.677197,15.047884,4.0,1.464509e+12,87.158924,50941692.0,0.0,...,11,7,1,0,1,0,0,1,0,0

In [25]:
test_new_data.head()

,featureA,featureB,featureC,featureD,featureE,featureF,featureG,featureH,featureI,compositionA,...,categoryE,unit,categoryB_catB_0,categoryB_catB_1,categoryD_catD_0,categoryD_catD_1,categoryD_catD_2,categoryF_catF_0,categoryF_catF_1,categoryF_catF_2
0,325435.125,1.728675,0.032407,274.708982,26.637511,0.0,2.757620e+12,0.000000,25867961.0,0.0,...,1,16,1,0,1,0,0,1,0,0
1,75808.375,4.457840,0.005718,122.299437,30.831906,0.0,2.806036e+12,0.000000,71176346.0,0.0,...,0,16,1,0,1,0,0,1,0,0
2,-19688.875,25.982190,0.000000,30.993471,17.510663,0.0,2.887150e+10,22.198357,1136923.0,3.6,...,8,4,1,0,1,0,0,1,0,0
3,75808.375,4.457840,0.005718,122.299437,30.831906,0.0,2.806036e+12,0.000000,71176346.0,0.0,...,0,0,1,0,1,0,0,1,0,0
4,-40055.250,4.363288,0.729194,93.677197,15.047884,0.0,1.464509e+12,87.158924,50941692.0,0.0,...,12,0,1,0,1,0,0,1,0,0

In [26]:
print(new_data.isnull().sum())

featureA            64
featureB            64
featureC            64
featureD            64
featureE            64
featureF             0
featureG            64
featureH            64
featureI            64
compositionA        64
compositionB        64
compositionC        64
compositionD        64
compositionE        64
compositionF        64
compositionG        64
compositionH        64
compositionI        64
compositionJ        64
categoryA            0
categoryC            0
categoryE            0
unit                 0
categoryB_catB_0     0
categoryB_catB_1     0
categoryD_catD_0     0
categoryD_catD_1     0
categoryD_catD_2     0
categoryF_catF_0     0
categoryF_catF_1     0
categoryF_catF_2     0
dtype: int64

In [27]:
null_columns = new_data.columns[new_data.isnull().any()]

test_null_columns = test_new_data.columns[test_new_data.isnull().any()]

In [28]:
for col in null_columns:
    new_data[col].fillna(value=new_data[col].mean(), inplace=True)
    
for test_col in test_null_columns:
    test_new_data[test_col].fillna(value=test_new_data[test_col].mean(), inplace=True)

In [29]:
print(new_data.isnull().sum())

featureA            0
featureB            0
featureC            0
featureD            0
featureE            0
featureF            0
featureG            0
featureH            0
featureI            0
compositionA        0
compositionB        0
compositionC        0
compositionD        0
compositionE        0
compositionF        0
compositionG        0
compositionH        0
compositionI        0
compositionJ        0
categoryA           0
categoryC           0
categoryE           0
unit                0
categoryB_catB_0    0
categoryB_catB_1    0
categoryD_catD_0    0
categoryD_catD_1    0
categoryD_catD_2    0
categoryF_catF_0    0
categoryF_catF_1    0
categoryF_catF_2    0
dtype: int64

In [30]:
print(test_new_data.isnull().sum())

featureA            0
featureB            0
featureC            0
featureD            0
featureE            0
featureF            0
featureG            0
featureH            0
featureI            0
compositionA        0
compositionB        0
compositionC        0
compositionD        0
compositionE        0
compositionF        0
compositionG        0
compositionH        0
compositionI        0
compositionJ        0
categoryA           0
categoryC           0
categoryE           0
unit                0
categoryB_catB_0    0
categoryB_catB_1    0
categoryD_catD_0    0
categoryD_catD_1    0
categoryD_catD_2    0
categoryF_catF_0    0
categoryF_catF_1    0
categoryF_catF_2    0
dtype: int64

In [31]:
# correleation
corr_new_data = pd.concat([new_data,y],axis=1)

In [32]:

features = new_data.columns.tolist()
target = y.name

In [33]:
from scipy.stats import pearsonr
correlations = {}
for f in features:
    data_temp = corr_new_data[[f,target]]
    x1 = data_temp[f].values
    x2 = data_temp[target].values
    key = f + ' vs ' + target
    correlations[key] = pearsonr(x1,x2)[0]

In [34]:
data_correlations = pd.DataFrame(correlations, index=['Value']).T
data_correlations.loc[data_correlations['Value'].abs().sort_values(ascending=False).index]

                               Value
categoryA vs result         0.445971
unit vs result              0.219455
categoryD_catD_1 vs result -0.090118
categoryD_catD_0 vs result  0.086773
compositionF vs result     -0.064246
compositionE vs result     -0.057422
compositionH vs result      0.055815
compositionA vs result      0.048526
featureA vs result          0.043572
compositionD vs result      0.039206
compositionG vs result      0.026676
featureC vs result         -0.025567
compositionJ vs result      0.024701
featureI vs result         -0.024654
compositionC vs result      0.023491
compositionI vs result      0.021939
featureH vs result         -0.019508
categoryB_catB_1 vs result -0.018640
categoryB_catB_0 vs result  0.018640
featureG vs result          0.017901
featureE vs result          0.017714
featureD vs result          0.016810
categoryF_catF_2 vs result -0.011237
featureF vs result          0.010264
categoryC vs result        -0.009264
compositionB vs result     -0.005922
categoryF_catF_1 vs result  0.003195
featureB vs result         -0.002855
categoryD_catD_2 vs result  0.001336
categoryE vs result         0.000942
categoryF_catF_0 vs result  0.000921

In [35]:
new_data = new_data.drop(['categoryF_catF_0','categoryE','categoryD_catD_2','featureB','categoryF_catF_1','compositionB','categoryC'],axis = 1)
test_new_data = test_new_data.drop(['categoryF_catF_0','categoryE','categoryD_catD_2','featureB','categoryF_catF_1','compositionB','categoryC'],axis = 1)

In [36]:
new_data

,featureA,featureC,featureD,featureE,featureF,featureG,featureH,featureI,compositionA,compositionC,...,compositionH,compositionI,compositionJ,categoryA,unit,categoryB_catB_0,categoryB_catB_1,categoryD_catD_0,categoryD_catD_1,categoryF_catF_2
0,75808.375,0.005718,122.299437,30.831906,0.0,2.806036e+12,0.000000,71176346.0,0.0,26.00,...,9.00,22.26,20.00,1,15,1,0,1,0,0
1,75808.375,0.005718,122.299437,30.831906,0.0,2.806036e+12,0.000000,71176346.0,0.0,26.00,...,9.00,22.26,20.00,1,15,1,0,1,0,0
2,75808.375,0.005718,122.299437,30.831906,0.0,2.806036e+12,0.000000,71176346.0,0.0,26.00,...,9.00,22.26,20.00,49,13,1,0,1,0,0
3,75808.375,0.005718,122.299437,30.831906,2.0,2.806036e+12,0.000000,71176346.0,0.0,26.00,...,9.00,22.26,20.00,0,14,1,0,1,0,0
4,-40055.250,0.729194,93.677197,15.047884,4.0,1.464509e+12,87.158924,50941692.0,0.0,14.00,...,9.00,16.84,15.00,82,7,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12995,75808.375,0.005718,122.299437,30.831906,0.0,2.806036e+12,0.000000,71176346.0,0.0,26.00,...,9.00,22.26,20.00,90,1,1,0,1,0,0
12996,75808.375,0.005718,122.299437,30.831906,0.0,2.806036e+12,0.000000,71176346.0,0.0,26.00,...,9.00,22.26,20.00,145,18,1,0,1,0,0
12997,75808.375,0.005718,122.299437,30.831906,0.0,2.806036e+12,0.000000,71176346.0,0.0,26.00,...,9.00,22.26,20.00,85,4,1,0,1,0,0
12998,18927.000,0.000387,18.148547,14.177182,0.0,2.526922e+11,0.000000,2147000.0,0.0,13.13,...,1.45,28.12,37.83,134,17,1,0,1,0,0
12999,18927.000,0.000387,18.148547,14.177182,0.0,2.526922e+11,0.000000,2147000.0,0.0,13.13,...,1.45,28.12,37.83,156,2,1,0,1,0,0

In [37]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# poly_dict = {}
# for feature in X.columns:
#     for p in range(2, 5):
#         X_train_poly = X
#         X_train_poly['sq'] = X_train_poly[feature] ** p
#         lr = LinearRegression()
#         lr.fit(X_train_poly, y)
#         poly_dict[lr.score(X_train_poly, y)] = [feature, p]
    
# poly_dict[max(poly_dict.keys())]

In [38]:
# X['categoryA_cube'] = X['categoryA']**3
# test_new_data['categoryA_cube'] = test_new_data['categoryA']**3

In [39]:
# X.drop('sq', axis = 1, inplace = True)

In [40]:
X_train, X_test, y_train, y_test = train_test_split(new_data, y, test_size = 0.25)

In [41]:
np.any(np.isnan(test_new_data))

False

In [42]:
np.all(np.isfinite(test_new_data))

True

In [43]:
test_new_data.replace([np.inf, -np.inf], np.nan, inplace=True)

In [44]:
model = LinearRegression()
  
model.fit(X_train, y_train)

LinearRegression()

In [45]:
test_preds = model.predict(test_new_data)

In [46]:
output = pd.DataFrame({'id': test.id,
                     'result': test_preds})
output.to_csv('water_quality_submission.csv', index=False)

### I hope you liked my notebook